### ISSUE TITLE
PC 8

### ISSUE THREAD

**Issue by JAntonioCoder** [SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-4as_coders#3]
[ACTIVIDAD 8 - TRABAJO EN EQUIPO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-4as_coders/files/15098691/ACTIVIDAD.8.-.TRABAJO.EN.EQUIPO.pdf)

**Comment by RodolfoNV** [comment]
Falto en detallar la información de el detalle de sus funciones de hilos.
Calificación 17

**Comment by josealfredo79** [comment]
bien hecho y revisado...
